# Generated by Django 4.2.11 on 2024-05-26 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("datetime_creat", models.DateField(auto_now_add=True)),
                ("datetime_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(verbose_name="comment text")),
                (
                    "stars",
                    models.CharField(
                        choices=[
                            ("1", "very bad"),
                            ("2", "bad"),
                            ("3", "normal"),
                            ("4", "good"),
                            ("5", "perfect"),
                        ],
                        max_length=10,
                        verbose_name=" your score?",
                    ),
                ),
                ("datetime_create", models.DateTimeField(auto_now_add=True)),
                ("datetime_modiefied", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="products.product",
                    ),
                ),
            ],
            managers=[
                ("active_comment_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
